// =============================================================================
// wb_imem.v — 2 KB Wishbone B4 classic instruction memory.
//
// Flat regfile-style memory (no OpenRAM, by project decision — see
// PHASE3_ARCHITECTURE.md §7). Loaded in simulation via $readmemh of the
// firmware hex generated by `objcopy -O verilog`. LibreLane init mechanism
// is Session 3E's choice.
//
// Sizing (Session 3E baseline rerun — 2026-05-04). The original 8 KB depth
// produced a 15 115-fanout read-mux net at OpenROAD that the resizer could
// not close at the slow corner (RSZ-0062). Shrinking to 2 KB / 512 words
// cuts the read-mux fanout ~4× and lets all three nominal corners close
// timing. The 1 556 B Phase-3D inference firmware fits with ~30 % headroom
// (492 B free); a Session 3.5 OpenRAM-backed rerun will revisit the depth.
//
// Wishbone B4 classic slave:
//   - ack_q registers a 1-cycle pulse on the first cycle of (cyc & stb).
//   - Reads return mem[adr[12:2]] combinationally; valid in the ack cycle.
//   - Writes are silently dropped. The interface acks normally so a stray
//     store does not hang the master, but the IMEM contents are unmodified.
//     (Promoting this to wb_err_o is deferred — picorv32_wb cannot consume
//     err anyway, and a hang would be the visible symptom either way.)
// =============================================================================
`default_nettype none

module wb_imem #(
    parameter integer SIZE_BYTES = 2048,
    parameter         INIT_HEX   = ""           // path to $readmemh file
) (
    input  wire        clk,
    input  wire        rst_n,

    input  wire        wb_cyc_i,
    input  wire        wb_stb_i,
    input  wire        wb_we_i,
    input  wire [3:0]  wb_sel_i,
    input  wire [31:0] wb_adr_i,
    input  wire [31:0] wb_dat_i,
    output wire [31:0] wb_dat_o,
    output wire        wb_ack_o,
    output wire        wb_err_o
);

    localparam integer WORDS = SIZE_BYTES / 4;
    localparam integer AW    = $clog2(WORDS);

    reg [31:0] mem [0:WORDS-1];

    integer ii;
    initial begin
        for (ii = 0; ii < WORDS; ii = ii + 1) mem[ii] = 32'b0;
        if (INIT_HEX != "") begin
            $readmemh(INIT_HEX, mem);
        end
    end

    // 1-cycle registered ack pulse.
    reg ack_q;
    always @(posedge clk) begin
        if (!rst_n)                            ack_q <= 1'b0;
        else if (wb_cyc_i & wb_stb_i & ~ack_q) ack_q <= 1'b1;
        else                                   ack_q <= 1'b0;
    end

    wire [AW-1:0] widx = wb_adr_i[AW+1:2];

    assign wb_ack_o = ack_q;
    assign wb_err_o = 1'b0;
    assign wb_dat_o = mem[widx];

    // wb_we_i / wb_dat_i / wb_sel_i are intentionally ignored — IMEM is RX.
    wire _unused_ok = &{1'b0, wb_we_i, wb_sel_i, wb_dat_i, 1'b0};

endmodule

`default_nettype wire
