// Auto-generated by gen_neuron.py — seed=4, variant=handopt
// Explicit 7-layer balanced adder-tree popcount, then compare.
`default_nettype none
module neuron_handopt_s4 (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h76a69242f403b25c;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire
