// Auto-generated by gen_tile.py — variant=handopt, mode=hardcoded, seed_id=2 (numpy seed 2), neurons=16.
// 16 BNN neurons, each implemented as a balanced adder-tree popcount.
`default_nettype none

`default_nettype none
module tile_handopt_hc_s2_n00_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h8f80787271c3faa6;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n01_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h62a3d92280143c6e;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n02_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h8e33bcc866bd787e;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n03_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h43a7781eaff2de9a;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n04_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'hd01d5c9be151b3f8;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n05_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h5b199b066bd7816f;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n06_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h21873c74a9c1ff24;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n07_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'hae625bbe1d50d29b;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n08_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h7271de53860cf821;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n09_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h217b80c3f0599849;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n10_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h226e52a4dfd81c8f;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n11_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'hb5563f34a9a483c9;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n12_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h416464c35793d3e7;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n13_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'hed10f083e6268f47;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n14_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'hd44725c4490ffd18;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


`default_nettype none
module tile_handopt_hc_s2_n15_neuron (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W = 64'h7ed4d1be664a5344;
    wire [63:0] m;
    assign m = x ^~ W;
    // L1: 32 partial sums of 2 bits each
    wire [1:0] s1_00 = m[0] + m[1];
    wire [1:0] s1_01 = m[2] + m[3];
    wire [1:0] s1_02 = m[4] + m[5];
    wire [1:0] s1_03 = m[6] + m[7];
    wire [1:0] s1_04 = m[8] + m[9];
    wire [1:0] s1_05 = m[10] + m[11];
    wire [1:0] s1_06 = m[12] + m[13];
    wire [1:0] s1_07 = m[14] + m[15];
    wire [1:0] s1_08 = m[16] + m[17];
    wire [1:0] s1_09 = m[18] + m[19];
    wire [1:0] s1_10 = m[20] + m[21];
    wire [1:0] s1_11 = m[22] + m[23];
    wire [1:0] s1_12 = m[24] + m[25];
    wire [1:0] s1_13 = m[26] + m[27];
    wire [1:0] s1_14 = m[28] + m[29];
    wire [1:0] s1_15 = m[30] + m[31];
    wire [1:0] s1_16 = m[32] + m[33];
    wire [1:0] s1_17 = m[34] + m[35];
    wire [1:0] s1_18 = m[36] + m[37];
    wire [1:0] s1_19 = m[38] + m[39];
    wire [1:0] s1_20 = m[40] + m[41];
    wire [1:0] s1_21 = m[42] + m[43];
    wire [1:0] s1_22 = m[44] + m[45];
    wire [1:0] s1_23 = m[46] + m[47];
    wire [1:0] s1_24 = m[48] + m[49];
    wire [1:0] s1_25 = m[50] + m[51];
    wire [1:0] s1_26 = m[52] + m[53];
    wire [1:0] s1_27 = m[54] + m[55];
    wire [1:0] s1_28 = m[56] + m[57];
    wire [1:0] s1_29 = m[58] + m[59];
    wire [1:0] s1_30 = m[60] + m[61];
    wire [1:0] s1_31 = m[62] + m[63];
    // L2: 16 partial sums of 3 bits each
    wire [2:0] s2_00 = s1_00 + s1_01;
    wire [2:0] s2_01 = s1_02 + s1_03;
    wire [2:0] s2_02 = s1_04 + s1_05;
    wire [2:0] s2_03 = s1_06 + s1_07;
    wire [2:0] s2_04 = s1_08 + s1_09;
    wire [2:0] s2_05 = s1_10 + s1_11;
    wire [2:0] s2_06 = s1_12 + s1_13;
    wire [2:0] s2_07 = s1_14 + s1_15;
    wire [2:0] s2_08 = s1_16 + s1_17;
    wire [2:0] s2_09 = s1_18 + s1_19;
    wire [2:0] s2_10 = s1_20 + s1_21;
    wire [2:0] s2_11 = s1_22 + s1_23;
    wire [2:0] s2_12 = s1_24 + s1_25;
    wire [2:0] s2_13 = s1_26 + s1_27;
    wire [2:0] s2_14 = s1_28 + s1_29;
    wire [2:0] s2_15 = s1_30 + s1_31;
    // L3: 8 partial sums of 4 bits each
    wire [3:0] s3_00 = s2_00 + s2_01;
    wire [3:0] s3_01 = s2_02 + s2_03;
    wire [3:0] s3_02 = s2_04 + s2_05;
    wire [3:0] s3_03 = s2_06 + s2_07;
    wire [3:0] s3_04 = s2_08 + s2_09;
    wire [3:0] s3_05 = s2_10 + s2_11;
    wire [3:0] s3_06 = s2_12 + s2_13;
    wire [3:0] s3_07 = s2_14 + s2_15;
    // L4: 4 partial sums of 5 bits each
    wire [4:0] s4_00 = s3_00 + s3_01;
    wire [4:0] s4_01 = s3_02 + s3_03;
    wire [4:0] s4_02 = s3_04 + s3_05;
    wire [4:0] s4_03 = s3_06 + s3_07;
    // L5: 2 partial sums of 6 bits each
    wire [5:0] s5_00 = s4_00 + s4_01;
    wire [5:0] s5_01 = s4_02 + s4_03;
    // L6: total popcount, 7 bits
    wire [6:0] total = s5_00 + s5_01;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire


module tile_handopt_hc_s2 (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [63:0] x_in,
    input  wire        x_valid,
    output wire [15:0] y_out,
    output wire        y_valid
);
    // 2-cycle pipeline: x_in -> x_reg -> [comb logic] -> y_out_r.
    // y_valid tracks the x_valid pulse through both flops.
    reg  [63:0] x_reg;
    reg  [15:0] y_out_r;
    reg         v_d1, v_d2;
    wire [15:0] y_comb;
    always @(posedge clk) begin
        if (!rst_n) begin
            x_reg   <= 64'b0;
            y_out_r <= 16'b0;
            v_d1    <= 1'b0;
            v_d2    <= 1'b0;
        end else begin
            if (x_valid) x_reg <= x_in;
            v_d1    <= x_valid;
            y_out_r <= y_comb;
            v_d2    <= v_d1;
        end
    end
    assign y_out   = y_out_r;
    assign y_valid = v_d2;

    tile_handopt_hc_s2_n00_neuron u_n00 (.x(x_reg), .y(y_comb[0]));
    tile_handopt_hc_s2_n01_neuron u_n01 (.x(x_reg), .y(y_comb[1]));
    tile_handopt_hc_s2_n02_neuron u_n02 (.x(x_reg), .y(y_comb[2]));
    tile_handopt_hc_s2_n03_neuron u_n03 (.x(x_reg), .y(y_comb[3]));
    tile_handopt_hc_s2_n04_neuron u_n04 (.x(x_reg), .y(y_comb[4]));
    tile_handopt_hc_s2_n05_neuron u_n05 (.x(x_reg), .y(y_comb[5]));
    tile_handopt_hc_s2_n06_neuron u_n06 (.x(x_reg), .y(y_comb[6]));
    tile_handopt_hc_s2_n07_neuron u_n07 (.x(x_reg), .y(y_comb[7]));
    tile_handopt_hc_s2_n08_neuron u_n08 (.x(x_reg), .y(y_comb[8]));
    tile_handopt_hc_s2_n09_neuron u_n09 (.x(x_reg), .y(y_comb[9]));
    tile_handopt_hc_s2_n10_neuron u_n10 (.x(x_reg), .y(y_comb[10]));
    tile_handopt_hc_s2_n11_neuron u_n11 (.x(x_reg), .y(y_comb[11]));
    tile_handopt_hc_s2_n12_neuron u_n12 (.x(x_reg), .y(y_comb[12]));
    tile_handopt_hc_s2_n13_neuron u_n13 (.x(x_reg), .y(y_comb[13]));
    tile_handopt_hc_s2_n14_neuron u_n14 (.x(x_reg), .y(y_comb[14]));
    tile_handopt_hc_s2_n15_neuron u_n15 (.x(x_reg), .y(y_comb[15]));
endmodule
`default_nettype wire
