// Auto-generated by gen_neuron.py — seed=3, variant=tlg
// Generic threshold-logic decomposition: 11 partial popcounts
// (10×6→3 + 1×4→3 truth tables), one summer, one comparator.
`default_nettype none

// chunk 0: 6 inputs, weight=0xc
module tlg_chunk6_s3_c00 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd4;
            6'd  1: pc = 3'd3;
            6'd  2: pc = 3'd3;
            6'd  3: pc = 3'd2;
            6'd  4: pc = 3'd5;
            6'd  5: pc = 3'd4;
            6'd  6: pc = 3'd4;
            6'd  7: pc = 3'd3;
            6'd  8: pc = 3'd5;
            6'd  9: pc = 3'd4;
            6'd 10: pc = 3'd4;
            6'd 11: pc = 3'd3;
            6'd 12: pc = 3'd6;
            6'd 13: pc = 3'd5;
            6'd 14: pc = 3'd5;
            6'd 15: pc = 3'd4;
            6'd 16: pc = 3'd3;
            6'd 17: pc = 3'd2;
            6'd 18: pc = 3'd2;
            6'd 19: pc = 3'd1;
            6'd 20: pc = 3'd4;
            6'd 21: pc = 3'd3;
            6'd 22: pc = 3'd3;
            6'd 23: pc = 3'd2;
            6'd 24: pc = 3'd4;
            6'd 25: pc = 3'd3;
            6'd 26: pc = 3'd3;
            6'd 27: pc = 3'd2;
            6'd 28: pc = 3'd5;
            6'd 29: pc = 3'd4;
            6'd 30: pc = 3'd4;
            6'd 31: pc = 3'd3;
            6'd 32: pc = 3'd3;
            6'd 33: pc = 3'd2;
            6'd 34: pc = 3'd2;
            6'd 35: pc = 3'd1;
            6'd 36: pc = 3'd4;
            6'd 37: pc = 3'd3;
            6'd 38: pc = 3'd3;
            6'd 39: pc = 3'd2;
            6'd 40: pc = 3'd4;
            6'd 41: pc = 3'd3;
            6'd 42: pc = 3'd3;
            6'd 43: pc = 3'd2;
            6'd 44: pc = 3'd5;
            6'd 45: pc = 3'd4;
            6'd 46: pc = 3'd4;
            6'd 47: pc = 3'd3;
            6'd 48: pc = 3'd2;
            6'd 49: pc = 3'd1;
            6'd 50: pc = 3'd1;
            6'd 51: pc = 3'd0;
            6'd 52: pc = 3'd3;
            6'd 53: pc = 3'd2;
            6'd 54: pc = 3'd2;
            6'd 55: pc = 3'd1;
            6'd 56: pc = 3'd3;
            6'd 57: pc = 3'd2;
            6'd 58: pc = 3'd2;
            6'd 59: pc = 3'd1;
            6'd 60: pc = 3'd4;
            6'd 61: pc = 3'd3;
            6'd 62: pc = 3'd3;
            6'd 63: pc = 3'd2;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 1: 6 inputs, weight=0x2e
module tlg_chunk6_s3_c01 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd2;
            6'd  1: pc = 3'd1;
            6'd  2: pc = 3'd3;
            6'd  3: pc = 3'd2;
            6'd  4: pc = 3'd3;
            6'd  5: pc = 3'd2;
            6'd  6: pc = 3'd4;
            6'd  7: pc = 3'd3;
            6'd  8: pc = 3'd3;
            6'd  9: pc = 3'd2;
            6'd 10: pc = 3'd4;
            6'd 11: pc = 3'd3;
            6'd 12: pc = 3'd4;
            6'd 13: pc = 3'd3;
            6'd 14: pc = 3'd5;
            6'd 15: pc = 3'd4;
            6'd 16: pc = 3'd1;
            6'd 17: pc = 3'd0;
            6'd 18: pc = 3'd2;
            6'd 19: pc = 3'd1;
            6'd 20: pc = 3'd2;
            6'd 21: pc = 3'd1;
            6'd 22: pc = 3'd3;
            6'd 23: pc = 3'd2;
            6'd 24: pc = 3'd2;
            6'd 25: pc = 3'd1;
            6'd 26: pc = 3'd3;
            6'd 27: pc = 3'd2;
            6'd 28: pc = 3'd3;
            6'd 29: pc = 3'd2;
            6'd 30: pc = 3'd4;
            6'd 31: pc = 3'd3;
            6'd 32: pc = 3'd3;
            6'd 33: pc = 3'd2;
            6'd 34: pc = 3'd4;
            6'd 35: pc = 3'd3;
            6'd 36: pc = 3'd4;
            6'd 37: pc = 3'd3;
            6'd 38: pc = 3'd5;
            6'd 39: pc = 3'd4;
            6'd 40: pc = 3'd4;
            6'd 41: pc = 3'd3;
            6'd 42: pc = 3'd5;
            6'd 43: pc = 3'd4;
            6'd 44: pc = 3'd5;
            6'd 45: pc = 3'd4;
            6'd 46: pc = 3'd6;
            6'd 47: pc = 3'd5;
            6'd 48: pc = 3'd2;
            6'd 49: pc = 3'd1;
            6'd 50: pc = 3'd3;
            6'd 51: pc = 3'd2;
            6'd 52: pc = 3'd3;
            6'd 53: pc = 3'd2;
            6'd 54: pc = 3'd4;
            6'd 55: pc = 3'd3;
            6'd 56: pc = 3'd3;
            6'd 57: pc = 3'd2;
            6'd 58: pc = 3'd4;
            6'd 59: pc = 3'd3;
            6'd 60: pc = 3'd4;
            6'd 61: pc = 3'd3;
            6'd 62: pc = 3'd5;
            6'd 63: pc = 3'd4;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 2: 6 inputs, weight=0x1b
module tlg_chunk6_s3_c02 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd2;
            6'd  1: pc = 3'd3;
            6'd  2: pc = 3'd3;
            6'd  3: pc = 3'd4;
            6'd  4: pc = 3'd1;
            6'd  5: pc = 3'd2;
            6'd  6: pc = 3'd2;
            6'd  7: pc = 3'd3;
            6'd  8: pc = 3'd3;
            6'd  9: pc = 3'd4;
            6'd 10: pc = 3'd4;
            6'd 11: pc = 3'd5;
            6'd 12: pc = 3'd2;
            6'd 13: pc = 3'd3;
            6'd 14: pc = 3'd3;
            6'd 15: pc = 3'd4;
            6'd 16: pc = 3'd3;
            6'd 17: pc = 3'd4;
            6'd 18: pc = 3'd4;
            6'd 19: pc = 3'd5;
            6'd 20: pc = 3'd2;
            6'd 21: pc = 3'd3;
            6'd 22: pc = 3'd3;
            6'd 23: pc = 3'd4;
            6'd 24: pc = 3'd4;
            6'd 25: pc = 3'd5;
            6'd 26: pc = 3'd5;
            6'd 27: pc = 3'd6;
            6'd 28: pc = 3'd3;
            6'd 29: pc = 3'd4;
            6'd 30: pc = 3'd4;
            6'd 31: pc = 3'd5;
            6'd 32: pc = 3'd1;
            6'd 33: pc = 3'd2;
            6'd 34: pc = 3'd2;
            6'd 35: pc = 3'd3;
            6'd 36: pc = 3'd0;
            6'd 37: pc = 3'd1;
            6'd 38: pc = 3'd1;
            6'd 39: pc = 3'd2;
            6'd 40: pc = 3'd2;
            6'd 41: pc = 3'd3;
            6'd 42: pc = 3'd3;
            6'd 43: pc = 3'd4;
            6'd 44: pc = 3'd1;
            6'd 45: pc = 3'd2;
            6'd 46: pc = 3'd2;
            6'd 47: pc = 3'd3;
            6'd 48: pc = 3'd2;
            6'd 49: pc = 3'd3;
            6'd 50: pc = 3'd3;
            6'd 51: pc = 3'd4;
            6'd 52: pc = 3'd1;
            6'd 53: pc = 3'd2;
            6'd 54: pc = 3'd2;
            6'd 55: pc = 3'd3;
            6'd 56: pc = 3'd3;
            6'd 57: pc = 3'd4;
            6'd 58: pc = 3'd4;
            6'd 59: pc = 3'd5;
            6'd 60: pc = 3'd2;
            6'd 61: pc = 3'd3;
            6'd 62: pc = 3'd3;
            6'd 63: pc = 3'd4;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 3: 6 inputs, weight=0x18
module tlg_chunk6_s3_c03 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd4;
            6'd  1: pc = 3'd3;
            6'd  2: pc = 3'd3;
            6'd  3: pc = 3'd2;
            6'd  4: pc = 3'd3;
            6'd  5: pc = 3'd2;
            6'd  6: pc = 3'd2;
            6'd  7: pc = 3'd1;
            6'd  8: pc = 3'd5;
            6'd  9: pc = 3'd4;
            6'd 10: pc = 3'd4;
            6'd 11: pc = 3'd3;
            6'd 12: pc = 3'd4;
            6'd 13: pc = 3'd3;
            6'd 14: pc = 3'd3;
            6'd 15: pc = 3'd2;
            6'd 16: pc = 3'd5;
            6'd 17: pc = 3'd4;
            6'd 18: pc = 3'd4;
            6'd 19: pc = 3'd3;
            6'd 20: pc = 3'd4;
            6'd 21: pc = 3'd3;
            6'd 22: pc = 3'd3;
            6'd 23: pc = 3'd2;
            6'd 24: pc = 3'd6;
            6'd 25: pc = 3'd5;
            6'd 26: pc = 3'd5;
            6'd 27: pc = 3'd4;
            6'd 28: pc = 3'd5;
            6'd 29: pc = 3'd4;
            6'd 30: pc = 3'd4;
            6'd 31: pc = 3'd3;
            6'd 32: pc = 3'd3;
            6'd 33: pc = 3'd2;
            6'd 34: pc = 3'd2;
            6'd 35: pc = 3'd1;
            6'd 36: pc = 3'd2;
            6'd 37: pc = 3'd1;
            6'd 38: pc = 3'd1;
            6'd 39: pc = 3'd0;
            6'd 40: pc = 3'd4;
            6'd 41: pc = 3'd3;
            6'd 42: pc = 3'd3;
            6'd 43: pc = 3'd2;
            6'd 44: pc = 3'd3;
            6'd 45: pc = 3'd2;
            6'd 46: pc = 3'd2;
            6'd 47: pc = 3'd1;
            6'd 48: pc = 3'd4;
            6'd 49: pc = 3'd3;
            6'd 50: pc = 3'd3;
            6'd 51: pc = 3'd2;
            6'd 52: pc = 3'd3;
            6'd 53: pc = 3'd2;
            6'd 54: pc = 3'd2;
            6'd 55: pc = 3'd1;
            6'd 56: pc = 3'd5;
            6'd 57: pc = 3'd4;
            6'd 58: pc = 3'd4;
            6'd 59: pc = 3'd3;
            6'd 60: pc = 3'd4;
            6'd 61: pc = 3'd3;
            6'd 62: pc = 3'd3;
            6'd 63: pc = 3'd2;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 4: 6 inputs, weight=0x4
module tlg_chunk6_s3_c04 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd5;
            6'd  1: pc = 3'd4;
            6'd  2: pc = 3'd4;
            6'd  3: pc = 3'd3;
            6'd  4: pc = 3'd6;
            6'd  5: pc = 3'd5;
            6'd  6: pc = 3'd5;
            6'd  7: pc = 3'd4;
            6'd  8: pc = 3'd4;
            6'd  9: pc = 3'd3;
            6'd 10: pc = 3'd3;
            6'd 11: pc = 3'd2;
            6'd 12: pc = 3'd5;
            6'd 13: pc = 3'd4;
            6'd 14: pc = 3'd4;
            6'd 15: pc = 3'd3;
            6'd 16: pc = 3'd4;
            6'd 17: pc = 3'd3;
            6'd 18: pc = 3'd3;
            6'd 19: pc = 3'd2;
            6'd 20: pc = 3'd5;
            6'd 21: pc = 3'd4;
            6'd 22: pc = 3'd4;
            6'd 23: pc = 3'd3;
            6'd 24: pc = 3'd3;
            6'd 25: pc = 3'd2;
            6'd 26: pc = 3'd2;
            6'd 27: pc = 3'd1;
            6'd 28: pc = 3'd4;
            6'd 29: pc = 3'd3;
            6'd 30: pc = 3'd3;
            6'd 31: pc = 3'd2;
            6'd 32: pc = 3'd4;
            6'd 33: pc = 3'd3;
            6'd 34: pc = 3'd3;
            6'd 35: pc = 3'd2;
            6'd 36: pc = 3'd5;
            6'd 37: pc = 3'd4;
            6'd 38: pc = 3'd4;
            6'd 39: pc = 3'd3;
            6'd 40: pc = 3'd3;
            6'd 41: pc = 3'd2;
            6'd 42: pc = 3'd2;
            6'd 43: pc = 3'd1;
            6'd 44: pc = 3'd4;
            6'd 45: pc = 3'd3;
            6'd 46: pc = 3'd3;
            6'd 47: pc = 3'd2;
            6'd 48: pc = 3'd3;
            6'd 49: pc = 3'd2;
            6'd 50: pc = 3'd2;
            6'd 51: pc = 3'd1;
            6'd 52: pc = 3'd4;
            6'd 53: pc = 3'd3;
            6'd 54: pc = 3'd3;
            6'd 55: pc = 3'd2;
            6'd 56: pc = 3'd2;
            6'd 57: pc = 3'd1;
            6'd 58: pc = 3'd1;
            6'd 59: pc = 3'd0;
            6'd 60: pc = 3'd3;
            6'd 61: pc = 3'd2;
            6'd 62: pc = 3'd2;
            6'd 63: pc = 3'd1;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 5: 6 inputs, weight=0x1a
module tlg_chunk6_s3_c05 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd3;
            6'd  1: pc = 3'd2;
            6'd  2: pc = 3'd4;
            6'd  3: pc = 3'd3;
            6'd  4: pc = 3'd2;
            6'd  5: pc = 3'd1;
            6'd  6: pc = 3'd3;
            6'd  7: pc = 3'd2;
            6'd  8: pc = 3'd4;
            6'd  9: pc = 3'd3;
            6'd 10: pc = 3'd5;
            6'd 11: pc = 3'd4;
            6'd 12: pc = 3'd3;
            6'd 13: pc = 3'd2;
            6'd 14: pc = 3'd4;
            6'd 15: pc = 3'd3;
            6'd 16: pc = 3'd4;
            6'd 17: pc = 3'd3;
            6'd 18: pc = 3'd5;
            6'd 19: pc = 3'd4;
            6'd 20: pc = 3'd3;
            6'd 21: pc = 3'd2;
            6'd 22: pc = 3'd4;
            6'd 23: pc = 3'd3;
            6'd 24: pc = 3'd5;
            6'd 25: pc = 3'd4;
            6'd 26: pc = 3'd6;
            6'd 27: pc = 3'd5;
            6'd 28: pc = 3'd4;
            6'd 29: pc = 3'd3;
            6'd 30: pc = 3'd5;
            6'd 31: pc = 3'd4;
            6'd 32: pc = 3'd2;
            6'd 33: pc = 3'd1;
            6'd 34: pc = 3'd3;
            6'd 35: pc = 3'd2;
            6'd 36: pc = 3'd1;
            6'd 37: pc = 3'd0;
            6'd 38: pc = 3'd2;
            6'd 39: pc = 3'd1;
            6'd 40: pc = 3'd3;
            6'd 41: pc = 3'd2;
            6'd 42: pc = 3'd4;
            6'd 43: pc = 3'd3;
            6'd 44: pc = 3'd2;
            6'd 45: pc = 3'd1;
            6'd 46: pc = 3'd3;
            6'd 47: pc = 3'd2;
            6'd 48: pc = 3'd3;
            6'd 49: pc = 3'd2;
            6'd 50: pc = 3'd4;
            6'd 51: pc = 3'd3;
            6'd 52: pc = 3'd2;
            6'd 53: pc = 3'd1;
            6'd 54: pc = 3'd3;
            6'd 55: pc = 3'd2;
            6'd 56: pc = 3'd4;
            6'd 57: pc = 3'd3;
            6'd 58: pc = 3'd5;
            6'd 59: pc = 3'd4;
            6'd 60: pc = 3'd3;
            6'd 61: pc = 3'd2;
            6'd 62: pc = 3'd4;
            6'd 63: pc = 3'd3;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 6: 6 inputs, weight=0x19
module tlg_chunk6_s3_c06 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd3;
            6'd  1: pc = 3'd4;
            6'd  2: pc = 3'd2;
            6'd  3: pc = 3'd3;
            6'd  4: pc = 3'd2;
            6'd  5: pc = 3'd3;
            6'd  6: pc = 3'd1;
            6'd  7: pc = 3'd2;
            6'd  8: pc = 3'd4;
            6'd  9: pc = 3'd5;
            6'd 10: pc = 3'd3;
            6'd 11: pc = 3'd4;
            6'd 12: pc = 3'd3;
            6'd 13: pc = 3'd4;
            6'd 14: pc = 3'd2;
            6'd 15: pc = 3'd3;
            6'd 16: pc = 3'd4;
            6'd 17: pc = 3'd5;
            6'd 18: pc = 3'd3;
            6'd 19: pc = 3'd4;
            6'd 20: pc = 3'd3;
            6'd 21: pc = 3'd4;
            6'd 22: pc = 3'd2;
            6'd 23: pc = 3'd3;
            6'd 24: pc = 3'd5;
            6'd 25: pc = 3'd6;
            6'd 26: pc = 3'd4;
            6'd 27: pc = 3'd5;
            6'd 28: pc = 3'd4;
            6'd 29: pc = 3'd5;
            6'd 30: pc = 3'd3;
            6'd 31: pc = 3'd4;
            6'd 32: pc = 3'd2;
            6'd 33: pc = 3'd3;
            6'd 34: pc = 3'd1;
            6'd 35: pc = 3'd2;
            6'd 36: pc = 3'd1;
            6'd 37: pc = 3'd2;
            6'd 38: pc = 3'd0;
            6'd 39: pc = 3'd1;
            6'd 40: pc = 3'd3;
            6'd 41: pc = 3'd4;
            6'd 42: pc = 3'd2;
            6'd 43: pc = 3'd3;
            6'd 44: pc = 3'd2;
            6'd 45: pc = 3'd3;
            6'd 46: pc = 3'd1;
            6'd 47: pc = 3'd2;
            6'd 48: pc = 3'd3;
            6'd 49: pc = 3'd4;
            6'd 50: pc = 3'd2;
            6'd 51: pc = 3'd3;
            6'd 52: pc = 3'd2;
            6'd 53: pc = 3'd3;
            6'd 54: pc = 3'd1;
            6'd 55: pc = 3'd2;
            6'd 56: pc = 3'd4;
            6'd 57: pc = 3'd5;
            6'd 58: pc = 3'd3;
            6'd 59: pc = 3'd4;
            6'd 60: pc = 3'd3;
            6'd 61: pc = 3'd4;
            6'd 62: pc = 3'd2;
            6'd 63: pc = 3'd3;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 7: 6 inputs, weight=0x2a
module tlg_chunk6_s3_c07 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd3;
            6'd  1: pc = 3'd2;
            6'd  2: pc = 3'd4;
            6'd  3: pc = 3'd3;
            6'd  4: pc = 3'd2;
            6'd  5: pc = 3'd1;
            6'd  6: pc = 3'd3;
            6'd  7: pc = 3'd2;
            6'd  8: pc = 3'd4;
            6'd  9: pc = 3'd3;
            6'd 10: pc = 3'd5;
            6'd 11: pc = 3'd4;
            6'd 12: pc = 3'd3;
            6'd 13: pc = 3'd2;
            6'd 14: pc = 3'd4;
            6'd 15: pc = 3'd3;
            6'd 16: pc = 3'd2;
            6'd 17: pc = 3'd1;
            6'd 18: pc = 3'd3;
            6'd 19: pc = 3'd2;
            6'd 20: pc = 3'd1;
            6'd 21: pc = 3'd0;
            6'd 22: pc = 3'd2;
            6'd 23: pc = 3'd1;
            6'd 24: pc = 3'd3;
            6'd 25: pc = 3'd2;
            6'd 26: pc = 3'd4;
            6'd 27: pc = 3'd3;
            6'd 28: pc = 3'd2;
            6'd 29: pc = 3'd1;
            6'd 30: pc = 3'd3;
            6'd 31: pc = 3'd2;
            6'd 32: pc = 3'd4;
            6'd 33: pc = 3'd3;
            6'd 34: pc = 3'd5;
            6'd 35: pc = 3'd4;
            6'd 36: pc = 3'd3;
            6'd 37: pc = 3'd2;
            6'd 38: pc = 3'd4;
            6'd 39: pc = 3'd3;
            6'd 40: pc = 3'd5;
            6'd 41: pc = 3'd4;
            6'd 42: pc = 3'd6;
            6'd 43: pc = 3'd5;
            6'd 44: pc = 3'd4;
            6'd 45: pc = 3'd3;
            6'd 46: pc = 3'd5;
            6'd 47: pc = 3'd4;
            6'd 48: pc = 3'd3;
            6'd 49: pc = 3'd2;
            6'd 50: pc = 3'd4;
            6'd 51: pc = 3'd3;
            6'd 52: pc = 3'd2;
            6'd 53: pc = 3'd1;
            6'd 54: pc = 3'd3;
            6'd 55: pc = 3'd2;
            6'd 56: pc = 3'd4;
            6'd 57: pc = 3'd3;
            6'd 58: pc = 3'd5;
            6'd 59: pc = 3'd4;
            6'd 60: pc = 3'd3;
            6'd 61: pc = 3'd2;
            6'd 62: pc = 3'd4;
            6'd 63: pc = 3'd3;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 8: 6 inputs, weight=0x17
module tlg_chunk6_s3_c08 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd2;
            6'd  1: pc = 3'd3;
            6'd  2: pc = 3'd3;
            6'd  3: pc = 3'd4;
            6'd  4: pc = 3'd3;
            6'd  5: pc = 3'd4;
            6'd  6: pc = 3'd4;
            6'd  7: pc = 3'd5;
            6'd  8: pc = 3'd1;
            6'd  9: pc = 3'd2;
            6'd 10: pc = 3'd2;
            6'd 11: pc = 3'd3;
            6'd 12: pc = 3'd2;
            6'd 13: pc = 3'd3;
            6'd 14: pc = 3'd3;
            6'd 15: pc = 3'd4;
            6'd 16: pc = 3'd3;
            6'd 17: pc = 3'd4;
            6'd 18: pc = 3'd4;
            6'd 19: pc = 3'd5;
            6'd 20: pc = 3'd4;
            6'd 21: pc = 3'd5;
            6'd 22: pc = 3'd5;
            6'd 23: pc = 3'd6;
            6'd 24: pc = 3'd2;
            6'd 25: pc = 3'd3;
            6'd 26: pc = 3'd3;
            6'd 27: pc = 3'd4;
            6'd 28: pc = 3'd3;
            6'd 29: pc = 3'd4;
            6'd 30: pc = 3'd4;
            6'd 31: pc = 3'd5;
            6'd 32: pc = 3'd1;
            6'd 33: pc = 3'd2;
            6'd 34: pc = 3'd2;
            6'd 35: pc = 3'd3;
            6'd 36: pc = 3'd2;
            6'd 37: pc = 3'd3;
            6'd 38: pc = 3'd3;
            6'd 39: pc = 3'd4;
            6'd 40: pc = 3'd0;
            6'd 41: pc = 3'd1;
            6'd 42: pc = 3'd1;
            6'd 43: pc = 3'd2;
            6'd 44: pc = 3'd1;
            6'd 45: pc = 3'd2;
            6'd 46: pc = 3'd2;
            6'd 47: pc = 3'd3;
            6'd 48: pc = 3'd2;
            6'd 49: pc = 3'd3;
            6'd 50: pc = 3'd3;
            6'd 51: pc = 3'd4;
            6'd 52: pc = 3'd3;
            6'd 53: pc = 3'd4;
            6'd 54: pc = 3'd4;
            6'd 55: pc = 3'd5;
            6'd 56: pc = 3'd1;
            6'd 57: pc = 3'd2;
            6'd 58: pc = 3'd2;
            6'd 59: pc = 3'd3;
            6'd 60: pc = 3'd2;
            6'd 61: pc = 3'd3;
            6'd 62: pc = 3'd3;
            6'd 63: pc = 3'd4;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 9: 6 inputs, weight=0xe
module tlg_chunk6_s3_c09 (
    input  wire [5:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            6'd  0: pc = 3'd3;
            6'd  1: pc = 3'd2;
            6'd  2: pc = 3'd4;
            6'd  3: pc = 3'd3;
            6'd  4: pc = 3'd4;
            6'd  5: pc = 3'd3;
            6'd  6: pc = 3'd5;
            6'd  7: pc = 3'd4;
            6'd  8: pc = 3'd4;
            6'd  9: pc = 3'd3;
            6'd 10: pc = 3'd5;
            6'd 11: pc = 3'd4;
            6'd 12: pc = 3'd5;
            6'd 13: pc = 3'd4;
            6'd 14: pc = 3'd6;
            6'd 15: pc = 3'd5;
            6'd 16: pc = 3'd2;
            6'd 17: pc = 3'd1;
            6'd 18: pc = 3'd3;
            6'd 19: pc = 3'd2;
            6'd 20: pc = 3'd3;
            6'd 21: pc = 3'd2;
            6'd 22: pc = 3'd4;
            6'd 23: pc = 3'd3;
            6'd 24: pc = 3'd3;
            6'd 25: pc = 3'd2;
            6'd 26: pc = 3'd4;
            6'd 27: pc = 3'd3;
            6'd 28: pc = 3'd4;
            6'd 29: pc = 3'd3;
            6'd 30: pc = 3'd5;
            6'd 31: pc = 3'd4;
            6'd 32: pc = 3'd2;
            6'd 33: pc = 3'd1;
            6'd 34: pc = 3'd3;
            6'd 35: pc = 3'd2;
            6'd 36: pc = 3'd3;
            6'd 37: pc = 3'd2;
            6'd 38: pc = 3'd4;
            6'd 39: pc = 3'd3;
            6'd 40: pc = 3'd3;
            6'd 41: pc = 3'd2;
            6'd 42: pc = 3'd4;
            6'd 43: pc = 3'd3;
            6'd 44: pc = 3'd4;
            6'd 45: pc = 3'd3;
            6'd 46: pc = 3'd5;
            6'd 47: pc = 3'd4;
            6'd 48: pc = 3'd1;
            6'd 49: pc = 3'd0;
            6'd 50: pc = 3'd2;
            6'd 51: pc = 3'd1;
            6'd 52: pc = 3'd2;
            6'd 53: pc = 3'd1;
            6'd 54: pc = 3'd3;
            6'd 55: pc = 3'd2;
            6'd 56: pc = 3'd2;
            6'd 57: pc = 3'd1;
            6'd 58: pc = 3'd3;
            6'd 59: pc = 3'd2;
            6'd 60: pc = 3'd3;
            6'd 61: pc = 3'd2;
            6'd 62: pc = 3'd4;
            6'd 63: pc = 3'd3;
            default: pc = 3'd0;
        endcase
    end
endmodule


// chunk 10: 4 inputs, weight=0x2
module tlg_chunk4_s3_c10 (
    input  wire [3:0] x,
    output reg  [2:0] pc
);
    always @* begin
        case (x)
            4'd  0: pc = 3'd3;
            4'd  1: pc = 3'd2;
            4'd  2: pc = 3'd4;
            4'd  3: pc = 3'd3;
            4'd  4: pc = 3'd2;
            4'd  5: pc = 3'd1;
            4'd  6: pc = 3'd3;
            4'd  7: pc = 3'd2;
            4'd  8: pc = 3'd2;
            4'd  9: pc = 3'd1;
            4'd 10: pc = 3'd3;
            4'd 11: pc = 3'd2;
            4'd 12: pc = 3'd1;
            4'd 13: pc = 3'd0;
            4'd 14: pc = 3'd2;
            4'd 15: pc = 3'd1;
            default: pc = 3'd0;
        endcase
    end
endmodule


module neuron_tlg_s3 (
    input  wire [63:0] x,
    output wire        y
);
    wire [2:0] pc00;
    tlg_chunk6_s3_c00 u00 (.x(x[5:0]), .pc(pc00));
    wire [2:0] pc01;
    tlg_chunk6_s3_c01 u01 (.x(x[11:6]), .pc(pc01));
    wire [2:0] pc02;
    tlg_chunk6_s3_c02 u02 (.x(x[17:12]), .pc(pc02));
    wire [2:0] pc03;
    tlg_chunk6_s3_c03 u03 (.x(x[23:18]), .pc(pc03));
    wire [2:0] pc04;
    tlg_chunk6_s3_c04 u04 (.x(x[29:24]), .pc(pc04));
    wire [2:0] pc05;
    tlg_chunk6_s3_c05 u05 (.x(x[35:30]), .pc(pc05));
    wire [2:0] pc06;
    tlg_chunk6_s3_c06 u06 (.x(x[41:36]), .pc(pc06));
    wire [2:0] pc07;
    tlg_chunk6_s3_c07 u07 (.x(x[47:42]), .pc(pc07));
    wire [2:0] pc08;
    tlg_chunk6_s3_c08 u08 (.x(x[53:48]), .pc(pc08));
    wire [2:0] pc09;
    tlg_chunk6_s3_c09 u09 (.x(x[59:54]), .pc(pc09));
    wire [2:0] pc10;
    tlg_chunk4_s3_c10 u10 (.x(x[63:60]), .pc(pc10));
    wire [6:0] total = pc00 + pc01 + pc02 + pc03 + pc04 + pc05 + pc06 + pc07 + pc08 + pc09 + pc10;
    assign y = (total >= 7'd32);
endmodule
`default_nettype wire
