#!/usr/bin/env python3
"""
gen_neuron.py — emit Verilog for the Phase-1 BNN neuron PPA experiment.

Function under test (identical across variants):

    y = (popcount(x XNOR W) >= THRESHOLD)         # W, THRESHOLD compile-time

with x, W: 64-bit (each bit ∈ {0,1} encoding ±1) and THRESHOLD=32 (the
midpoint, fixed across all seeds — we are comparing synthesis methodologies,
not training networks).

Three implementations of the same function:

  naive    — `assign y = ($countones(x ^~ W) >= THRESHOLD);`
              The lazy baseline. Yosys+ABC pick the structure.

  handopt  — explicit balanced 7-layer adder tree:
              64 → 32(2b) → 16(3b) → 8(4b) → 4(5b) → 2(6b) → 1(7b) → compare.
              The "fair fight" baseline an experienced RTL designer would write.

  tlg      — generic threshold-logic decomposition: 11 chunks (10 of size 6,
              one of size 4), each chunk's partial popcount expressed as an
              explicit truth-table `case` (so ABC can map the 6→3 LUT freely),
              then a simple sum + comparator on the 11 partials.

Run:
    python gen_neuron.py naive    --seed N --out rtl/naive/
    python gen_neuron.py handopt  --seed N --out rtl/handopt/
    python gen_neuron.py tlg      --seed N --out rtl/tlg/
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

N_INPUTS = 64
THRESHOLD = 32
CHUNK_SIZE = 6  # 10 chunks of 6 + 1 chunk of 4 = 64


def gen_weights(seed: int) -> np.ndarray:
    rng = np.random.RandomState(seed)
    return rng.randint(0, 2, size=N_INPUTS).astype(np.uint8)


def w_to_int(w_bits: np.ndarray) -> int:
    """Pack a bit array (LSB at index 0) into an integer."""
    return int(sum(int(b) << i for i, b in enumerate(w_bits)))


def reference_y(x_int: int, w_int: int, threshold: int = THRESHOLD) -> int:
    """Python golden model: 1 iff popcount(x XNOR w) >= threshold."""
    mask = (1 << N_INPUTS) - 1
    xnor = (~(x_int ^ w_int)) & mask
    return int(bin(xnor).count("1") >= threshold)


# ----------------------------------------------------------------------
# Variant A — naive
# ----------------------------------------------------------------------

def emit_naive(seed: int) -> str:
    w = gen_weights(seed)
    w_int = w_to_int(w)
    name = f"neuron_naive_s{seed}"
    return f"""// Auto-generated by gen_neuron.py — seed={seed}, variant=naive
// y = (popcount(x XNOR W) >= 32). W and threshold are compile-time constants.
`default_nettype none
module {name} (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W      = 64'h{w_int:016x};
    localparam [6:0]  THRESH = 7'd{THRESHOLD};

    // SystemVerilog $countones — Yosys reduces this however it wants.
    assign y = ($countones(x ^~ W) >= THRESH);
endmodule
`default_nettype wire
"""


# ----------------------------------------------------------------------
# Variant B — hand-optimized balanced adder tree
# ----------------------------------------------------------------------

def emit_handopt(seed: int) -> str:
    w = gen_weights(seed)
    w_int = w_to_int(w)
    name = f"neuron_handopt_s{seed}"

    out = []
    out.append(f"// Auto-generated by gen_neuron.py — seed={seed}, variant=handopt")
    out.append("// Explicit 7-layer balanced adder-tree popcount, then compare.")
    out.append("`default_nettype none")
    out.append(f"module {name} (")
    out.append("    input  wire [63:0] x,")
    out.append("    output wire        y")
    out.append(");")
    out.append(f"    localparam [63:0] W = 64'h{w_int:016x};")
    out.append("    wire [63:0] m;")
    out.append("    assign m = x ^~ W;")

    # Layer 1: 64 1b → 32 2b
    out.append("    // L1: 32 partial sums of 2 bits each")
    for i in range(32):
        out.append(f"    wire [1:0] s1_{i:02d} = m[{2*i}] + m[{2*i+1}];")
    # Layer 2: 32 2b → 16 3b
    out.append("    // L2: 16 partial sums of 3 bits each")
    for i in range(16):
        out.append(f"    wire [2:0] s2_{i:02d} = s1_{2*i:02d} + s1_{2*i+1:02d};")
    # Layer 3: 16 3b → 8 4b
    out.append("    // L3: 8 partial sums of 4 bits each")
    for i in range(8):
        out.append(f"    wire [3:0] s3_{i:02d} = s2_{2*i:02d} + s2_{2*i+1:02d};")
    # Layer 4: 8 4b → 4 5b
    out.append("    // L4: 4 partial sums of 5 bits each")
    for i in range(4):
        out.append(f"    wire [4:0] s4_{i:02d} = s3_{2*i:02d} + s3_{2*i+1:02d};")
    # Layer 5: 4 5b → 2 6b
    out.append("    // L5: 2 partial sums of 6 bits each")
    for i in range(2):
        out.append(f"    wire [5:0] s5_{i:02d} = s4_{2*i:02d} + s4_{2*i+1:02d};")
    # Layer 6: 2 6b → 1 7b (the total popcount)
    out.append("    // L6: total popcount, 7 bits")
    out.append("    wire [6:0] total = s5_00 + s5_01;")
    out.append(f"    assign y = (total >= 7'd{THRESHOLD});")
    out.append("endmodule")
    out.append("`default_nettype wire")
    return "\n".join(out) + "\n"


# ----------------------------------------------------------------------
# Variant C — TLG decomposition (generic, weight-vector agnostic)
# ----------------------------------------------------------------------

def emit_tlg_chunk_module(chunk_size: int, seed: int, chunk_idx: int,
                          chunk_w: np.ndarray) -> str:
    """A single chunk: combinational truth table mapping `size` inputs to
    a 3-bit partial popcount of (x XNOR chunk_w).

    Implemented as `always @* case (x) ... endcase` so Yosys treats this as
    an opaque 6→3 (or 4→3) function and ABC has full freedom to map it onto
    sky130_fd_sc_hd cells.
    """
    name = f"tlg_chunk{chunk_size}_s{seed}_c{chunk_idx:02d}"
    w_int = w_to_int(chunk_w)  # constant within this chunk
    mask = (1 << chunk_size) - 1

    out = [f"// chunk {chunk_idx}: {chunk_size} inputs, weight=0x{w_int:x}",
           f"module {name} (",
           f"    input  wire [{chunk_size-1}:0] x,",
           "    output reg  [2:0] pc",
           ");",
           "    always @* begin",
           "        case (x)"]
    for v in range(1 << chunk_size):
        xnor_v = (~(v ^ w_int)) & mask
        pc_val = bin(xnor_v).count("1")
        out.append(f"            {chunk_size}'d{v:>3}: pc = 3'd{pc_val};")
    out.append("            default: pc = 3'd0;")
    out.append("        endcase")
    out.append("    end")
    out.append("endmodule")
    return "\n".join(out) + "\n"


def emit_tlg(seed: int) -> str:
    w = gen_weights(seed)
    name = f"neuron_tlg_s{seed}"

    # Partition 64 inputs into 10 chunks of 6 + 1 chunk of 4.
    chunks = []  # list of (lo, hi, chunk_w_bits, chunk_size)
    bit = 0
    for ci in range(10):
        chunks.append((bit, bit + CHUNK_SIZE, w[bit:bit + CHUNK_SIZE], CHUNK_SIZE))
        bit += CHUNK_SIZE
    # Final chunk of size 4.
    chunks.append((bit, bit + 4, w[bit:bit + 4], 4))
    bit += 4
    assert bit == N_INPUTS

    out = [f"// Auto-generated by gen_neuron.py — seed={seed}, variant=tlg",
           "// Generic threshold-logic decomposition: 11 partial popcounts",
           "// (10×6→3 + 1×4→3 truth tables), one summer, one comparator.",
           "`default_nettype none",
           ""]

    # Emit chunk modules.
    for ci, (lo, hi, cw, csz) in enumerate(chunks):
        out.append(emit_tlg_chunk_module(csz, seed, ci, cw))
        out.append("")

    # Emit top.
    out.append(f"module {name} (")
    out.append("    input  wire [63:0] x,")
    out.append("    output wire        y")
    out.append(");")
    for ci, (lo, hi, _, csz) in enumerate(chunks):
        out.append(f"    wire [2:0] pc{ci:02d};")
        out.append(f"    tlg_chunk{csz}_s{seed}_c{ci:02d} u{ci:02d} "
                   f"(.x(x[{hi-1}:{lo}]), .pc(pc{ci:02d}));")
    pc_terms = " + ".join(f"pc{ci:02d}" for ci in range(len(chunks)))
    out.append(f"    wire [6:0] total = {pc_terms};")
    out.append(f"    assign y = (total >= 7'd{THRESHOLD});")
    out.append("endmodule")
    out.append("`default_nettype wire")
    return "\n".join(out) + "\n"


# ----------------------------------------------------------------------

EMIT = {"naive": emit_naive, "handopt": emit_handopt, "tlg": emit_tlg}


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("variant", choices=sorted(EMIT))
    p.add_argument("--seed", type=int, required=True)
    p.add_argument("--out", type=Path, required=True,
                   help="output directory; the file is named neuron_<variant>_s<seed>.v")
    args = p.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    fname = args.out / f"neuron_{args.variant}_s{args.seed}.v"
    fname.write_text(EMIT[args.variant](args.seed))
    print(f"wrote {fname}")


if __name__ == "__main__":
    main()
