# Phase 3E — activity-aware power on the post-P&R SoC for one corner,
# with hierarchical decomposition.
#
# Inputs (set by the caller via env):
#   STA_LIB                 — sky130 .lib for this corner
#   STA_NETLIST             — flow/phase3_soc/runs/.../final/nl/soc_top.nl.v
#   STA_TOP                 — soc_top
#   STA_SDC                 — flow/common/soc.sdc
#   STA_SPEF                — corner-specific SPEF parasitics
#   STA_VCD                 — VCD from tb_soc_bnn (+vcd plus-arg run)
#   STA_VCD_SCOPE           — tb_soc_bnn/dut
#   STA_CORNER_NAME         — e.g. max_ff_n40C_1v95
#   STA_REPORT_DIR          — where to drop power.rpt + power.metrics.json
#   STA_BUCKET_DIR          — results/phase3/power/buckets/  (cell-list files)
#
# Reuses the Phase-2C OpenSTA standalone flow (read_liberty / read_verilog
# / link_design / read_sdc / read_spef / read_power_activities) and adds a
# per-bucket loop that calls sta::instance_power for each cell in each
# bucket and sums the four power components.

set lib_file       $::env(STA_LIB)
set netlist_file   $::env(STA_NETLIST)
set top_module     $::env(STA_TOP)
set sdc_file       $::env(STA_SDC)
set spef_file      $::env(STA_SPEF)
set vcd_file       $::env(STA_VCD)
set vcd_scope      $::env(STA_VCD_SCOPE)
set corner_name    $::env(STA_CORNER_NAME)
set report_dir     $::env(STA_REPORT_DIR)
set bucket_dir     $::env(STA_BUCKET_DIR)

file mkdir $report_dir

set_cmd_units \
    -time ns \
    -capacitance pF \
    -current mA \
    -voltage V \
    -resistance kOhm \
    -distance um

define_corners $corner_name
read_liberty -corner $corner_name $lib_file
# Macro Liberties — LibreLane 3.x ships these only for the TT corner; all
# 9 corners load the same TT macro lib (documented limitation, see
# PHASE3_5_NOTES.md).
if {[info exists ::env(STA_EXTRA_LIBS)]} {
    foreach extra_lib [split $::env(STA_EXTRA_LIBS) ":"] {
        if {$extra_lib ne ""} {
            puts "Reading extra Liberty: $extra_lib"
            read_liberty -corner $corner_name $extra_lib
        }
    }
}
read_verilog $netlist_file
link_design $top_module
read_sdc $sdc_file
read_spef -corner $corner_name $spef_file
read_power_activities -scope $vcd_scope -vcd $vcd_file

# Apply per-net activities for interior signals — OpenSTA's read_vcd
# only annotates design *port* pins, not interior pins, so combinational
# power collapses to ~0 without this step. The TCL is generated by
# scripts/vcd_to_activity_tcl.py from the same flat VCD.
set activities_tcl [file join $bucket_dir "activities.tcl"]
if {[file exists $activities_tcl]} {
    puts "Sourcing interior-pin activities from $activities_tcl"
    source $activities_tcl
}

set corner_obj [sta::find_corner $corner_name]

# ---- Whole-design power ------------------------------------------------
set design_pw [sta::design_power $corner_obj]
set d_internal  [lindex $design_pw 0]
set d_switching [lindex $design_pw 1]
set d_leakage   [lindex $design_pw 2]
set d_total     [lindex $design_pw 3]

# ---- Per-group power (Sequential / Combinational / Clock / Macro / Pad)
# sta::report_power_design_json prints JSON as a side-effect but returns "";
# parsing its return value corrupts TCL state in LibreLane 3.0.3 OpenSTA.
# Skip the per-group breakdown — design_power totals are sufficient.
set group_totals [dict create]

# ---- Per-bucket power --------------------------------------------------
# Read each bucket's cell list, look up each instance, sum power.
# sta::instance_power returns {internal switching leakage total} in W.
set bucket_names {u_cpu u_xbar u_imem u_dmem u_tile u_gpio shared clock_tree}
set bucket_results [dict create]

foreach b $bucket_names {
    set fp [open [file join $bucket_dir "$b.cells"] r]
    set t_int 0.0
    set t_sw  0.0
    set t_lk  0.0
    set t_tot 0.0
    set n_found 0
    set n_missing 0
    while {[gets $fp line] >= 0} {
        set name [string trim $line]
        if {$name eq ""} { continue }
        # Cell instance names are flat (no escaped identifiers) post-flatten.
        set inst [get_cells -quiet $name]
        if {$inst eq ""} {
            incr n_missing
            continue
        }
        set p [sta::instance_power $inst $corner_obj]
        set t_int [expr {$t_int + [lindex $p 0]}]
        set t_sw  [expr {$t_sw  + [lindex $p 1]}]
        set t_lk  [expr {$t_lk  + [lindex $p 2]}]
        set t_tot [expr {$t_tot + [lindex $p 3]}]
        incr n_found
    }
    close $fp
    dict set bucket_results $b [list $t_int $t_sw $t_lk $t_tot $n_found $n_missing]
}

# ---- Text report -------------------------------------------------------
set rpt_path [file join $report_dir power.rpt]
set fp [open $rpt_path w]
puts $fp "===== Phase 3E activity-aware power (SoC, post-P&R)"
puts $fp "  top:           $top_module"
puts $fp "  corner:        $corner_name"
puts $fp "  liberty:       $lib_file"
puts $fp "  netlist:       $netlist_file"
puts $fp "  spef:          $spef_file"
puts $fp "  vcd:           $vcd_file"
puts $fp "  vcd_scope:     $vcd_scope"
puts $fp "============================================================="
puts $fp ""
puts $fp [format "%-15s %14s %14s %14s %14s" \
            "Group" "Internal(W)" "Switching(W)" "Leakage(W)" "Total(W)"]
puts $fp [string repeat - 75]
foreach grp {Sequential Combinational Clock Macro Pad} {
    if {![dict exists $group_totals $grp]} { continue }
    set g [dict get $group_totals $grp]
    puts $fp [format "%-15s %14.4e %14.4e %14.4e %14.4e" \
                $grp [lindex $g 0] [lindex $g 1] [lindex $g 2] [lindex $g 3]]
}
puts $fp [string repeat - 75]
puts $fp [format "%-15s %14.4e %14.4e %14.4e %14.4e" \
            "Total" $d_internal $d_switching $d_leakage $d_total]
puts $fp ""
puts $fp "----- Per-bucket (hierarchy-decomposed) ---------------------"
puts $fp [format "%-12s %14s %14s %14s %14s %8s" \
            "Bucket" "Internal(W)" "Switching(W)" "Leakage(W)" "Total(W)" "#cells"]
puts $fp [string repeat - 80]
set sum_buckets 0.0
foreach b $bucket_names {
    set r [dict get $bucket_results $b]
    set t_int [lindex $r 0]
    set t_sw  [lindex $r 1]
    set t_lk  [lindex $r 2]
    set t_tot [lindex $r 3]
    set n_found [lindex $r 4]
    set n_missing [lindex $r 5]
    set sum_buckets [expr {$sum_buckets + $t_tot}]
    puts $fp [format "%-12s %14.4e %14.4e %14.4e %14.4e %8d" \
                $b $t_int $t_sw $t_lk $t_tot $n_found]
    if {$n_missing > 0} {
        puts $fp [format "  (warning: %d cell names not found in netlist for bucket %s)" \
                    $n_missing $b]
    }
}
puts $fp [string repeat - 80]
puts $fp [format "%-12s %58.4e" "Bucket sum" $sum_buckets]
puts $fp [format "%-12s %58.4e" "Design total" $d_total]
puts $fp [format "%-12s %58.4e" "Δ (unbucketed)" [expr {$d_total - $sum_buckets}]]
close $fp

# ---- JSON metrics -----------------------------------------------------
set jp [open [file join $report_dir power.metrics.json] w]
puts $jp "{"
puts $jp "  \"corner\": \"$corner_name\","
puts $jp "  \"top\": \"$top_module\","
puts $jp "  \"power__internal__total\": $d_internal,"
puts $jp "  \"power__switching__total\": $d_switching,"
puts $jp "  \"power__leakage__total\": $d_leakage,"
puts $jp "  \"power__total\": $d_total,"
puts $jp "  \"groups\": {"
set first 1
foreach grp {Sequential Combinational Clock Macro Pad} {
    if {![dict exists $group_totals $grp]} { continue }
    set g [dict get $group_totals $grp]
    if {!$first} { puts $jp "    ," }
    puts $jp "    \"$grp\": { \"internal\": [lindex $g 0], \"switching\": [lindex $g 1], \"leakage\": [lindex $g 2], \"total\": [lindex $g 3] }"
    set first 0
}
puts $jp "  },"
puts $jp "  \"buckets\": {"
set first 1
foreach b $bucket_names {
    set r [dict get $bucket_results $b]
    if {!$first} { puts $jp "    ," }
    puts $jp "    \"$b\": { \"internal\": [lindex $r 0], \"switching\": [lindex $r 1], \"leakage\": [lindex $r 2], \"total\": [lindex $r 3], \"cells_found\": [lindex $r 4], \"cells_missing\": [lindex $r 5] }"
    set first 0
}
puts $jp "  }"
puts $jp "}"
close $jp

puts ""
puts "STA_SOC_POWER_DONE corner=$corner_name total=$d_total bucket_sum=$sum_buckets"
