"""Emit firmware/inference/weights.h from data/bnn_weights.npz.

Layout written:

    static const uint32_t L1_W_LO[HIDDEN_BATCHES][16];    // bits [31: 0]
    static const uint32_t L1_W_HI[HIDDEN_BATCHES][16];    // bits [63:32] (incl. PAD_WEIGHT_BITS)
    static const uint8_t  L1_T   [HIDDEN_BATCHES][16];    // 0..49 (popcount-≥ threshold)
    static const uint32_t L2_W_LO[N_OUTPUT];              // bits [31: 0] (no padding)
    static const uint32_t L2_W_HI[N_OUTPUT];              // bits [63:32]
    static const int16_t  L2_BIAS[N_OUTPUT];              // signed argmax bias

HIDDEN_BATCHES = 4 = 64 hidden / 16 neurons per tile evaluation.

Layer-1 weight packing convention (must match scripts/bnn_reference.py):
  bits [48: 0] = (w + 1)/2 in LSB-first order over the 49 trained inputs
  bits [63:49] = 1            (PAD_WEIGHT_BITS — gives zero popcount
                               contribution when paired with PAD_INPUT_BITS = 0)
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import bnn_reference as ref           # noqa: E402

N_INPUT  = ref.N_INPUT
N_HIDDEN = ref.N_HIDDEN
N_OUTPUT = ref.N_OUTPUT
HIDDEN_BATCHES = N_HIDDEN // 16              # 4


def _pack_l1(w_pm1_row: np.ndarray) -> tuple[int, int]:
    word = ref.pack_weight_l1(w_pm1_row)     # 64-bit Python int (with pad bits)
    return int(word & 0xFFFFFFFF), int((word >> 32) & 0xFFFFFFFF)


def _pack_l2(w_pm1_row: np.ndarray) -> tuple[int, int]:
    word = ref.pack_weight_l2(w_pm1_row)
    return int(word & 0xFFFFFFFF), int((word >> 32) & 0xFFFFFFFF)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--net",     choices=["7x7", "14x14"], default="7x7")
    p.add_argument("--weights", default=None,
                   help="npz path (default: data/bnn_weights[_14x14].npz)")
    p.add_argument("--out",     default=None,
                   help="header path (default: firmware/inference/weights[_14x14].h)")
    args = p.parse_args()

    net14 = (args.net == "14x14")
    if args.weights is None:
        args.weights = ("data/bnn_weights_14x14.npz" if net14
                        else "data/bnn_weights.npz")
    if args.out is None:
        args.out = ("firmware/inference/weights_14x14.h" if net14
                    else "firmware/inference/weights.h")

    net = ref.load_bnn(args.weights)
    if net["l1_w"].shape != (N_HIDDEN, N_INPUT):
        raise ValueError(f"unexpected l1_w shape {net['l1_w'].shape}")
    if net["l2_w"].shape != (N_OUTPUT, N_HIDDEN):
        raise ValueError(f"unexpected l2_w shape {net['l2_w'].shape}")

    # Pack layer 1 in batched (k, i) order. k = tile-evaluation index (0..3),
    # i = within-batch neuron index (0..15). Hidden neuron index = 16*k + i.
    l1_lo = np.zeros((HIDDEN_BATCHES, 16), dtype=np.uint32)
    l1_hi = np.zeros((HIDDEN_BATCHES, 16), dtype=np.uint32)
    l1_t  = np.zeros((HIDDEN_BATCHES, 16), dtype=np.uint8)
    for k in range(HIDDEN_BATCHES):
        for i in range(16):
            lo, hi = _pack_l1(net["l1_w"][16 * k + i])
            l1_lo[k, i] = lo
            l1_hi[k, i] = hi
            l1_t [k, i] = int(net["l1_t"][16 * k + i])

    l2_lo = np.zeros(N_OUTPUT, dtype=np.uint32)
    l2_hi = np.zeros(N_OUTPUT, dtype=np.uint32)
    for c in range(N_OUTPUT):
        lo, hi = _pack_l2(net["l2_w"][c])
        l2_lo[c] = lo
        l2_hi[c] = hi
    l2_bias = net["l2_bias"].astype(np.int16)

    out = []
    out.append("/* AUTOGENERATED by scripts/weights_to_c.py — do not edit. */")
    out.append("#ifndef WEIGHTS_H")
    out.append("#define WEIGHTS_H")
    out.append("")
    out.append(f"#define HIDDEN_BATCHES {HIDDEN_BATCHES}")
    out.append(f"#define N_OUTPUT       {N_OUTPUT}")
    out.append("")
    # L1 weights.
    out.append("static const unsigned int L1_W_LO[HIDDEN_BATCHES][16] = {")
    for k in range(HIDDEN_BATCHES):
        row = ", ".join(f"0x{int(l1_lo[k, i]):08x}u" for i in range(16))
        out.append(f"    {{ {row} }},")
    out.append("};")
    out.append("static const unsigned int L1_W_HI[HIDDEN_BATCHES][16] = {")
    for k in range(HIDDEN_BATCHES):
        row = ", ".join(f"0x{int(l1_hi[k, i]):08x}u" for i in range(16))
        out.append(f"    {{ {row} }},")
    out.append("};")
    out.append("static const unsigned char L1_T[HIDDEN_BATCHES][16] = {")
    for k in range(HIDDEN_BATCHES):
        row = ", ".join(f"{int(l1_t[k, i]):3d}" for i in range(16))
        out.append(f"    {{ {row} }},")
    out.append("};")
    out.append("")
    # L2 weights + bias.
    out.append("static const unsigned int L2_W_LO[N_OUTPUT] = {")
    out.append("    " + ", ".join(f"0x{int(l2_lo[c]):08x}u" for c in range(N_OUTPUT)))
    out.append("};")
    out.append("static const unsigned int L2_W_HI[N_OUTPUT] = {")
    out.append("    " + ", ".join(f"0x{int(l2_hi[c]):08x}u" for c in range(N_OUTPUT)))
    out.append("};")
    out.append("static const short L2_BIAS[N_OUTPUT] = {")
    out.append("    " + ", ".join(f"{int(l2_bias[c]):4d}" for c in range(N_OUTPUT)))
    out.append("};")
    out.append("")
    out.append("#endif /* WEIGHTS_H */")
    out.append("")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out))
    print(f"wrote {out_path} (HIDDEN_BATCHES={HIDDEN_BATCHES}, N_OUTPUT={N_OUTPUT}, "
          f"l1_t [{int(l1_t.min())}..{int(l1_t.max())}], "
          f"l2_bias [{int(l2_bias.min())}..{int(l2_bias.max())}])")


if __name__ == "__main__":
    main()
