// =============================================================================
// tb_wb_tile_wrapper.sv — directed Wishbone testbench for wb_tile_wrapper.
//
// Drives the Phase-3B wrapper through its Wishbone B4 classic slave interface
// (NOT through internal signals — only debug observers reach into the DUT)
// and runs ten scenarios covering the spec's functional surface:
//
//   T1  reset hygiene
//   T2  single weight write (W[0])
//   T3  all 16 weights — cfg log clean
//   T4  all 16 thresholds — cfg log clean
//   T5  single inference end-to-end
//   T6  100 back-to-back inferences vs Python golden
//   T7  concurrent-write drop while BUSY=1
//   T8  out-of-order HI without prior LO  (documented "LO=0" path)
//   T9  read-back of writable registers
//   T10 write to undefined address — silent ignore
//
// Final summary: "TILE WRAPPER FUNCTIONAL CHECK: PASS (10/10)" or a numbered
// failure line per failed test plus a non-zero $finish via $fatal.
//
// Data files (generated by scripts/wb_tile_reference.py): tb_wb_ws.hex,
// tb_wb_ts.hex, tb_wb_xs.hex, tb_wb_ys.hex — read via $readmemh from the TB
// working directory (the run script `cd tb` before vvp).
// =============================================================================
`timescale 1ns/1ps
`default_nettype none

module tb_wb_tile_wrapper;
    localparam integer N_NEURONS = 16;
    localparam integer N_VEC     = 100;

    // Slave-relative offsets within the 512 B tile window. The wrapper only
    // looks at adr[8:0]; we don't need to OR in 0x2000_0000 in this TB.
    localparam [31:0] W_LO_BASE = 32'h0000_0000;
    localparam [31:0] W_HI_BASE = 32'h0000_0004;
    localparam [31:0] T_BASE    = 32'h0000_0080;
    localparam [31:0] XIN_LO    = 32'h0000_0100;
    localparam [31:0] XIN_HI    = 32'h0000_0104;
    localparam [31:0] STATUS    = 32'h0000_0108;
    localparam [31:0] YOUT      = 32'h0000_010C;
    localparam [31:0] CTRL      = 32'h0000_0110;
    localparam [31:0] RSVD_CTRL = 32'h0000_0114;   // ctrl region, undefined
    localparam [31:0] RSVD_HI   = 32'h0000_0180;   // upper reserved region

    // ------------------------------------------------------------------------
    // Clock / reset / WB master regs.
    // ------------------------------------------------------------------------
    reg clk = 1'b0;
    always #5 clk = ~clk;       // 100 MHz

    reg         rst_n;
    reg [31:0]  m_adr, m_dat;
    reg         m_cyc, m_stb, m_we;
    reg [3:0]   m_sel;
    wire [31:0] s_dat;
    wire        s_ack, s_err;

    wb_tile_wrapper dut (
        .clk      (clk),
        .rst_n    (rst_n),
        .wb_cyc_i (m_cyc),
        .wb_stb_i (m_stb),
        .wb_we_i  (m_we),
        .wb_sel_i (m_sel),
        .wb_adr_i (m_adr),
        .wb_dat_i (m_dat),
        .wb_dat_o (s_dat),
        .wb_ack_o (s_ack),
        .wb_err_o (s_err)
    );

    // ------------------------------------------------------------------------
    // Cfg-bus monitor (debug-only observer; tests assert against bus output,
    // but a few scenarios additionally check that cfg_we / x_valid pulsed
    // exactly the expected number of times — that has no other observable
    // outside the wrapper's internals).
    // ------------------------------------------------------------------------
    reg [5:0]  cfg_addr_log  [0:127];
    reg [63:0] cfg_wdata_log [0:127];
    integer cfg_log_count;
    integer x_valid_pulses;

    always @(posedge clk) begin
        if (rst_n && dut.tile_cfg_we) begin
            cfg_addr_log[cfg_log_count]  <= dut.tile_cfg_addr;
            cfg_wdata_log[cfg_log_count] <= dut.tile_cfg_wdata;
            cfg_log_count                <= cfg_log_count + 1;
        end
        if (rst_n && dut.tile_x_valid)
            x_valid_pulses <= x_valid_pulses + 1;
    end

    task automatic clear_monitor;
        begin
            cfg_log_count  = 0;
            x_valid_pulses = 0;
        end
    endtask

    // ------------------------------------------------------------------------
    // WB master primitives. Convention: drive at negedge so the slave samples
    // a stable value at the next posedge; settle past NBA with `#1` after
    // each posedge wait.
    // ------------------------------------------------------------------------
    task automatic wb_idle;
        begin
            m_cyc = 1'b0;
            m_stb = 1'b0;
            m_we  = 1'b0;
            m_sel = 4'b0;
            m_adr = 32'b0;
            m_dat = 32'b0;
        end
    endtask

    task automatic wb_write(input [31:0] adr, input [31:0] dat);
        begin
            @(negedge clk);
            m_adr = adr; m_dat = dat;
            m_cyc = 1'b1; m_stb = 1'b1; m_we = 1'b1; m_sel = 4'hF;
            do begin
                @(posedge clk); #1;
            end while (s_ack !== 1'b1);
            @(negedge clk);
            wb_idle();
        end
    endtask

    // Back-to-back write: holds stb asserted between calls so consecutive
    // bus transactions land 2 cycles apart with no idle gap. Caller releases
    // the bus by calling `wb_release_chain()` at the end of the chain.
    task automatic wb_write_chain(input [31:0] adr, input [31:0] dat);
        begin
            @(negedge clk);
            m_adr = adr; m_dat = dat;
            m_cyc = 1'b1; m_stb = 1'b1; m_we = 1'b1; m_sel = 4'hF;
            do begin
                @(posedge clk); #1;
            end while (s_ack !== 1'b1);
        end
    endtask

    task automatic wb_release_chain;
        begin
            @(negedge clk);
            wb_idle();
        end
    endtask

    task automatic wb_read(input [31:0] adr, output [31:0] rd);
        begin
            @(negedge clk);
            m_adr = adr;
            m_cyc = 1'b1; m_stb = 1'b1; m_we = 1'b0; m_sel = 4'hF;
            do begin
                @(posedge clk); #1;
            end while (s_ack !== 1'b1);
            rd = s_dat;
            @(negedge clk);
            wb_idle();
        end
    endtask

    // ------------------------------------------------------------------------
    // BNN reference data (loaded once from $readmemh).
    // ------------------------------------------------------------------------
    reg [63:0] w_set [0:N_NEURONS-1];
    reg [6:0]  t_set [0:N_NEURONS-1];
    reg [63:0] xs    [0:N_VEC-1];
    reg [15:0] ys    [0:N_VEC-1];

    // ------------------------------------------------------------------------
    // Test result tracking.
    // ------------------------------------------------------------------------
    integer pass_count;
    integer fail_count;

    // ------------------------------------------------------------------------
    // Compound helpers.
    // ------------------------------------------------------------------------
    task automatic program_weights;
        integer k;
        begin
            for (k = 0; k < N_NEURONS; k = k + 1) begin
                wb_write(W_LO_BASE + 8*k, w_set[k][31:0]);
                wb_write(W_HI_BASE + 8*k, w_set[k][63:32]);
            end
        end
    endtask

    task automatic program_thresholds;
        integer k;
        begin
            for (k = 0; k < N_NEURONS; k = k + 1)
                wb_write(T_BASE + 4*k, {25'b0, t_set[k]});
        end
    endtask

    task automatic poll_until_done(output [31:0] status);
        integer guard;
        begin
            guard = 0;
            do begin
                wb_read(STATUS, status);
                guard = guard + 1;
                if (guard > 200) $fatal(1, "poll_until_done: timeout (BUSY never cleared)");
            end while ((status & 32'h2) == 0);
        end
    endtask

    task automatic do_inference(input [63:0] xv, output [15:0] yv);
        reg [31:0] status, yword;
        begin
            wb_write(XIN_LO, xv[31:0]);
            wb_write(XIN_HI, xv[63:32]);
            poll_until_done(status);
            wb_read(YOUT, yword);
            yv = yword[15:0];
            wb_write(CTRL, 32'h1);  // CLR_DONE
        end
    endtask

    // ------------------------------------------------------------------------
    // Main test sequencer.
    // ------------------------------------------------------------------------
    integer    k, mismatches;
    reg [31:0] rd, rd2, status_val;
    reg [15:0] y_obs;
    reg        test_ok;
    reg [63:0] ref_wdata;

    initial begin
        $readmemh("tb_wb_ws.hex", w_set);
        $readmemh("tb_wb_ts.hex", t_set);
        $readmemh("tb_wb_xs.hex", xs);
        $readmemh("tb_wb_ys.hex", ys);

        rst_n = 1'b0;
        wb_idle();
        clear_monitor();
        pass_count = 0;
        fail_count = 0;
        repeat (4) @(posedge clk);
        rst_n = 1'b1;
        @(posedge clk); #1;

        // ====================================================================
        // T1: reset hygiene — STATUS=0, YOUT=0, no x_valid pulses since reset.
        // ====================================================================
        clear_monitor();
        wb_read(STATUS, rd);
        wb_read(YOUT,   rd2);
        test_ok = (rd == 32'b0) && (rd2 == 32'b0) && (x_valid_pulses == 0);
        if (test_ok) begin
            pass_count = pass_count + 1;
            $display("[PASS] T1 reset hygiene: STATUS=%08x YOUT=%08x", rd, rd2);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T1 reset hygiene: STATUS=%08x YOUT=%08x xv_pulses=%0d",
                     rd, rd2, x_valid_pulses);
        end

        // ====================================================================
        // T2: single weight write — LO produces no cfg activity, HI produces
        //     exactly one cfg_we pulse with cfg_addr=0, cfg_wdata={HI,LO}.
        // ====================================================================
        clear_monitor();
        wb_write(W_LO_BASE, 32'hDEAD_BEEF);
        // After LO alone: no cfg activity allowed.
        if (cfg_log_count != 0)
            $display("  T2 (warning) LO write produced cfg pulse — logic bug");
        wb_write(W_HI_BASE, 32'hCAFE_BABE);
        ref_wdata = 64'hCAFEBABE_DEADBEEF;
        test_ok = (cfg_log_count == 1) &&
                  (cfg_addr_log[0]  == 6'b00_0000) &&
                  (cfg_wdata_log[0] == ref_wdata);
        if (test_ok) begin
            pass_count = pass_count + 1;
            $display("[PASS] T2 single weight W[0]: cfg_we#%0d addr=%h wdata=%h",
                     cfg_log_count, cfg_addr_log[0], cfg_wdata_log[0]);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T2 single weight W[0]: cfg_we#%0d addr=%h wdata=%h (exp %h)",
                     cfg_log_count, cfg_addr_log[0], cfg_wdata_log[0], ref_wdata);
        end

        // ====================================================================
        // T3: all 16 weights — 16 cfg_we pulses, address 0..15, wdata=w_set[i].
        // ====================================================================
        clear_monitor();
        program_weights();
        mismatches = 0;
        if (cfg_log_count != 16) mismatches = mismatches + 1;
        for (k = 0; k < 16; k = k + 1) begin
            if (cfg_addr_log[k]  !== {2'b00, k[3:0]})  mismatches = mismatches + 1;
            if (cfg_wdata_log[k] !== w_set[k])         mismatches = mismatches + 1;
        end
        if (mismatches == 0) begin
            pass_count = pass_count + 1;
            $display("[PASS] T3 all 16 weights programmed (cfg log clean, %0d pulses)",
                     cfg_log_count);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T3 all 16 weights: %0d mismatch(es), log_count=%0d",
                     mismatches, cfg_log_count);
        end

        // ====================================================================
        // T4: all 16 thresholds — 16 cfg_we pulses, addr 16..31, wdata[6:0]=t_set[i].
        // ====================================================================
        clear_monitor();
        program_thresholds();
        mismatches = 0;
        if (cfg_log_count != 16) mismatches = mismatches + 1;
        for (k = 0; k < 16; k = k + 1) begin
            if (cfg_addr_log[k]       !== {2'b01, k[3:0]}) mismatches = mismatches + 1;
            if (cfg_wdata_log[k][6:0] !== t_set[k])        mismatches = mismatches + 1;
        end
        if (mismatches == 0) begin
            pass_count = pass_count + 1;
            $display("[PASS] T4 all 16 thresholds programmed (cfg log clean, %0d pulses)",
                     cfg_log_count);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T4 all 16 thresholds: %0d mismatch(es), log_count=%0d",
                     mismatches, cfg_log_count);
        end

        // ====================================================================
        // T5: single inference end-to-end vs Python golden (xs[0] → ys[0]).
        // ====================================================================
        clear_monitor();
        do_inference(xs[0], y_obs);
        test_ok = (y_obs == ys[0]) && (x_valid_pulses == 1);
        if (test_ok) begin
            pass_count = pass_count + 1;
            $display("[PASS] T5 inference vec[0]: x=%h y=%04h (exp %04h, xv_pulses=%0d)",
                     xs[0], y_obs, ys[0], x_valid_pulses);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T5 inference vec[0]: x=%h y=%04h (exp %04h, xv_pulses=%0d)",
                     xs[0], y_obs, ys[0], x_valid_pulses);
        end

        // ====================================================================
        // T6: 100 back-to-back inferences vs Python golden.
        // ====================================================================
        mismatches = 0;
        for (k = 0; k < N_VEC; k = k + 1) begin
            do_inference(xs[k], y_obs);
            if (y_obs !== ys[k]) begin
                if (mismatches < 5)
                    $display("  T6 mismatch vec[%0d]: x=%h y=%04h exp=%04h",
                             k, xs[k], y_obs, ys[k]);
                mismatches = mismatches + 1;
            end
        end
        if (mismatches == 0) begin
            pass_count = pass_count + 1;
            $display("[PASS] T6 %0d back-to-back inferences", N_VEC);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T6 inferences: %0d mismatches out of %0d", mismatches, N_VEC);
        end

        // ====================================================================
        // T7: concurrent-write drop. Sequence:
        //   - Standard XIN.LO write for vec0 (xs[10]).
        //   - Chain XIN.HI_vec0 then XIN.HI_vec1 (xs[20][63:32]) back-to-back.
        //   - The vec1 HI bus_wr lands at posedge X+2 with busy=1 → dropped.
        //   - Verify: yout matches ys[10]; only ONE x_valid pulse fired.
        //     (If vec1 had also fired, x_valid_pulses would be 2 and the
        //      captured yout could match ys[20] instead.)
        // ====================================================================
        clear_monitor();
        wb_write(XIN_LO, xs[10][31:0]);
        x_valid_pulses = 0;
        wb_write_chain(XIN_HI, xs[10][63:32]);   // commits vec0 → busy<=1
        wb_write_chain(XIN_HI, xs[20][63:32]);   // dropped: lands while busy=1
        wb_release_chain();
        poll_until_done(status_val);
        wb_read(YOUT, rd);
        y_obs = rd[15:0];
        wb_write(CTRL, 32'h1);                   // CLR_DONE for next test
        test_ok = (y_obs == ys[10]) &&
                  (x_valid_pulses == 1) &&
                  (y_obs !== ys[20]);
        if (test_ok) begin
            pass_count = pass_count + 1;
            $display("[PASS] T7 concurrent drop: yout=%04h (vec0 ref=%04h, vec1 ref=%04h, xv=%0d)",
                     y_obs, ys[10], ys[20], x_valid_pulses);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T7 concurrent drop: yout=%04h (vec0=%04h, vec1=%04h, xv=%0d)",
                     y_obs, ys[10], ys[20], x_valid_pulses);
        end

        // ====================================================================
        // T8: out-of-order HI without prior LO. Documented behavior is
        //     "LO shadow holds whatever value was last written (or 0 from
        //     reset)" — verify cfg pulse fires with cfg_wdata={HI, 0}.
        //     Use SOFT_RESET first to force w_lo_shadow[5] = 0.
        // ====================================================================
        wb_write(CTRL, 32'h2);                   // SOFT_RESET → all shadows = 0
        clear_monitor();
        wb_write(W_HI_BASE + 8*5, 32'h12345678); // W[5].HI without prior LO
        ref_wdata = {32'h12345678, 32'h0};
        test_ok = (cfg_log_count == 1) &&
                  (cfg_addr_log[0]  == 6'b00_0101) &&
                  (cfg_wdata_log[0] == ref_wdata);
        if (test_ok) begin
            pass_count = pass_count + 1;
            $display("[PASS] T8 HI-without-LO: addr=%h wdata=%h (LO shadow=0 path)",
                     cfg_addr_log[0], cfg_wdata_log[0]);
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T8 HI-without-LO: cfg#%0d addr=%h wdata=%h (exp %h)",
                     cfg_log_count, cfg_addr_log[0], cfg_wdata_log[0], ref_wdata);
        end

        // ====================================================================
        // T9: read-back of writable registers. Self-contained — SOFT_RESET
        //     first so we read what we just wrote.
        // ====================================================================
        wb_write(CTRL, 32'h2);   // SOFT_RESET
        test_ok = 1'b1;

        wb_write(W_LO_BASE + 8*3, 32'hAAAA_1111);
        wb_write(W_HI_BASE + 8*3, 32'hBBBB_2222);
        wb_read (W_LO_BASE + 8*3, rd); test_ok = test_ok && (rd == 32'hAAAA_1111);
        wb_read (W_HI_BASE + 8*3, rd); test_ok = test_ok && (rd == 32'hBBBB_2222);

        wb_write(T_BASE + 4*7, 32'h0000_0040);
        wb_read (T_BASE + 4*7, rd);    test_ok = test_ok && (rd == 32'h0000_0040);

        wb_write(XIN_LO, 32'h0123_4567);
        wb_read (XIN_LO, rd);          test_ok = test_ok && (rd == 32'h0123_4567);

        // XIN.HI shadow read-back: write commits an inference, but the shadow
        // captures the data and is readable post-completion.
        wb_write(XIN_HI, 32'h89AB_CDEF);
        poll_until_done(status_val);
        wb_read (XIN_HI, rd);          test_ok = test_ok && (rd == 32'h89AB_CDEF);
        wb_write(CTRL, 32'h1);         // CLR_DONE so T10 starts clean

        if (test_ok) begin
            pass_count = pass_count + 1;
            $display("[PASS] T9 read-back of writable regs (W.LO/HI, T, XIN.LO/HI)");
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T9 read-back: at least one shadow did not return its written value");
        end

        // ====================================================================
        // T10: writes to undefined addresses — silent ignore (ack but no
        //     cfg_we / x_valid pulse, no shadow change visible to T9-style
        //     read-back).
        // ====================================================================
        clear_monitor();
        x_valid_pulses = 0;
        wb_write(RSVD_CTRL, 32'hDEAD_BEEF);  // 0x114, in ctrl region but undefined
        wb_write(RSVD_HI,   32'h1234_5678);  // 0x180, in upper reserved region
        wb_read (RSVD_CTRL, rd);
        wb_read (RSVD_HI,   rd2);
        test_ok = (cfg_log_count == 0) && (x_valid_pulses == 0) &&
                  (rd == 32'b0) && (rd2 == 32'b0);
        if (test_ok) begin
            pass_count = pass_count + 1;
            $display("[PASS] T10 reserved writes silently ignored, reads return 0");
        end else begin
            fail_count = fail_count + 1;
            $display("[FAIL] T10 reserved access: cfg#%0d xv=%0d rd1=%h rd2=%h",
                     cfg_log_count, x_valid_pulses, rd, rd2);
        end

        // ====================================================================
        // Final summary.
        // ====================================================================
        $display("---");
        if (fail_count == 0) begin
            $display("TILE WRAPPER FUNCTIONAL CHECK: PASS (%0d/%0d)",
                     pass_count, pass_count + fail_count);
            $finish;
        end else begin
            $display("TILE WRAPPER FUNCTIONAL CHECK: FAIL (%0d passed, %0d failed)",
                     pass_count, fail_count);
            $fatal(1, "wrapper TB failures");
        end
    end

    // Watchdog — abort if simulation runs unreasonably long. 100 inferences
    // take ~2 K cycles (~20 us at 100 MHz); 5 ms is a 250x safety margin.
    initial begin
        #5_000_000;
        $display("[FATAL] simulation watchdog timeout (5 ms)");
        $fatal(1, "watchdog");
    end

endmodule

`default_nettype wire
