// Auto-generated by gen_neuron.py — seed=4, variant=naive
// y = (popcount(x XNOR W) >= 32). W and threshold are compile-time constants.
`default_nettype none
module neuron_naive_s4 (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W      = 64'h76a69242f403b25c;
    localparam [6:0]  THRESH = 7'd32;

    // SystemVerilog $countones — Yosys reduces this however it wants.
    assign y = ($countones(x ^~ W) >= THRESH);
endmodule
`default_nettype wire
