// Auto-generated by gen_neuron.py — seed=1, variant=naive
// y = (popcount(x XNOR W) >= 32). W and threshold are compile-time constants.
`default_nettype none
module neuron_naive_s1 (
    input  wire [63:0] x,
    output wire        y
);
    localparam [63:0] W      = 64'h65c9bf1f112269f3;
    localparam [6:0]  THRESH = 7'd32;

    // SystemVerilog $countones — Yosys reduces this however it wants.
    assign y = ($countones(x ^~ W) >= THRESH);
endmodule
`default_nettype wire
