// Auto-generated by gen_tile.py — variant=tlg, mode=loadable, neurons=16.
// Generic TLG decomposition: weights/thresholds in a config regfile.
`default_nettype none

module tile_tlg_ld_chunk6 (
    input  wire [5:0] x,
    input  wire [5:0] w,
    output reg  [2:0] pc
);
    wire [5:0] m = x ^~ w;
    always @* begin
        case (m)
            6'd  0: pc = 3'd0;
            6'd  1: pc = 3'd1;
            6'd  2: pc = 3'd1;
            6'd  3: pc = 3'd2;
            6'd  4: pc = 3'd1;
            6'd  5: pc = 3'd2;
            6'd  6: pc = 3'd2;
            6'd  7: pc = 3'd3;
            6'd  8: pc = 3'd1;
            6'd  9: pc = 3'd2;
            6'd 10: pc = 3'd2;
            6'd 11: pc = 3'd3;
            6'd 12: pc = 3'd2;
            6'd 13: pc = 3'd3;
            6'd 14: pc = 3'd3;
            6'd 15: pc = 3'd4;
            6'd 16: pc = 3'd1;
            6'd 17: pc = 3'd2;
            6'd 18: pc = 3'd2;
            6'd 19: pc = 3'd3;
            6'd 20: pc = 3'd2;
            6'd 21: pc = 3'd3;
            6'd 22: pc = 3'd3;
            6'd 23: pc = 3'd4;
            6'd 24: pc = 3'd2;
            6'd 25: pc = 3'd3;
            6'd 26: pc = 3'd3;
            6'd 27: pc = 3'd4;
            6'd 28: pc = 3'd3;
            6'd 29: pc = 3'd4;
            6'd 30: pc = 3'd4;
            6'd 31: pc = 3'd5;
            6'd 32: pc = 3'd1;
            6'd 33: pc = 3'd2;
            6'd 34: pc = 3'd2;
            6'd 35: pc = 3'd3;
            6'd 36: pc = 3'd2;
            6'd 37: pc = 3'd3;
            6'd 38: pc = 3'd3;
            6'd 39: pc = 3'd4;
            6'd 40: pc = 3'd2;
            6'd 41: pc = 3'd3;
            6'd 42: pc = 3'd3;
            6'd 43: pc = 3'd4;
            6'd 44: pc = 3'd3;
            6'd 45: pc = 3'd4;
            6'd 46: pc = 3'd4;
            6'd 47: pc = 3'd5;
            6'd 48: pc = 3'd2;
            6'd 49: pc = 3'd3;
            6'd 50: pc = 3'd3;
            6'd 51: pc = 3'd4;
            6'd 52: pc = 3'd3;
            6'd 53: pc = 3'd4;
            6'd 54: pc = 3'd4;
            6'd 55: pc = 3'd5;
            6'd 56: pc = 3'd3;
            6'd 57: pc = 3'd4;
            6'd 58: pc = 3'd4;
            6'd 59: pc = 3'd5;
            6'd 60: pc = 3'd4;
            6'd 61: pc = 3'd5;
            6'd 62: pc = 3'd5;
            6'd 63: pc = 3'd6;
            default: pc = 3'd0;
        endcase
    end
endmodule


module tile_tlg_ld_chunk4 (
    input  wire [3:0] x,
    input  wire [3:0] w,
    output reg  [2:0] pc
);
    wire [3:0] m = x ^~ w;
    always @* begin
        case (m)
            4'd  0: pc = 3'd0;
            4'd  1: pc = 3'd1;
            4'd  2: pc = 3'd1;
            4'd  3: pc = 3'd2;
            4'd  4: pc = 3'd1;
            4'd  5: pc = 3'd2;
            4'd  6: pc = 3'd2;
            4'd  7: pc = 3'd3;
            4'd  8: pc = 3'd1;
            4'd  9: pc = 3'd2;
            4'd 10: pc = 3'd2;
            4'd 11: pc = 3'd3;
            4'd 12: pc = 3'd2;
            4'd 13: pc = 3'd3;
            4'd 14: pc = 3'd3;
            4'd 15: pc = 3'd4;
            default: pc = 3'd0;
        endcase
    end
endmodule


module tile_tlg_ld_neuron (
    input  wire [63:0] x,
    input  wire [63:0] w,
    input  wire [6:0]  threshold,
    output wire        y
);
    wire [2:0] pc00;
    tile_tlg_ld_chunk6 u00 (.x(x[5:0]), .w(w[5:0]), .pc(pc00));
    wire [2:0] pc01;
    tile_tlg_ld_chunk6 u01 (.x(x[11:6]), .w(w[11:6]), .pc(pc01));
    wire [2:0] pc02;
    tile_tlg_ld_chunk6 u02 (.x(x[17:12]), .w(w[17:12]), .pc(pc02));
    wire [2:0] pc03;
    tile_tlg_ld_chunk6 u03 (.x(x[23:18]), .w(w[23:18]), .pc(pc03));
    wire [2:0] pc04;
    tile_tlg_ld_chunk6 u04 (.x(x[29:24]), .w(w[29:24]), .pc(pc04));
    wire [2:0] pc05;
    tile_tlg_ld_chunk6 u05 (.x(x[35:30]), .w(w[35:30]), .pc(pc05));
    wire [2:0] pc06;
    tile_tlg_ld_chunk6 u06 (.x(x[41:36]), .w(w[41:36]), .pc(pc06));
    wire [2:0] pc07;
    tile_tlg_ld_chunk6 u07 (.x(x[47:42]), .w(w[47:42]), .pc(pc07));
    wire [2:0] pc08;
    tile_tlg_ld_chunk6 u08 (.x(x[53:48]), .w(w[53:48]), .pc(pc08));
    wire [2:0] pc09;
    tile_tlg_ld_chunk6 u09 (.x(x[59:54]), .w(w[59:54]), .pc(pc09));
    wire [2:0] pc10;
    tile_tlg_ld_chunk4 u10 (.x(x[63:60]), .w(w[63:60]), .pc(pc10));
    wire [6:0] total = pc00 + pc01 + pc02 + pc03 + pc04 + pc05 + pc06 + pc07 + pc08 + pc09 + pc10;
    assign y = (total >= threshold);
endmodule


module tile_tlg_ld (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [63:0] x_in,
    input  wire        x_valid,
    output wire [15:0] y_out,
    output wire        y_valid,
    input  wire        cfg_we,
    input  wire [5:0]  cfg_addr,
    input  wire [63:0] cfg_wdata
);
    // 2-cycle pipeline: x_in -> x_reg -> [comb logic] -> y_out_r.
    // y_valid tracks the x_valid pulse through both flops.
    reg  [63:0] x_reg;
    reg  [15:0] y_out_r;
    reg         v_d1, v_d2;
    wire [15:0] y_comb;
    always @(posedge clk) begin
        if (!rst_n) begin
            x_reg   <= 64'b0;
            y_out_r <= 16'b0;
            v_d1    <= 1'b0;
            v_d2    <= 1'b0;
        end else begin
            if (x_valid) x_reg <= x_in;
            v_d1    <= x_valid;
            y_out_r <= y_comb;
            v_d2    <= v_d1;
        end
    end
    assign y_out   = y_out_r;
    assign y_valid = v_d2;

    // Configuration register file: cfg_addr[5:4]==2'b00 selects
    // weight regs (0..15), 2'b01 selects threshold regs (16..31).
    reg [63:0] w_reg [0:15];
    reg [6:0]  t_reg [0:15];
    integer _i;
    always @(posedge clk) begin
        if (!rst_n) begin
            for (_i = 0; _i < 16; _i = _i + 1) begin
                w_reg[_i] <= 64'b0;
                t_reg[_i] <= 7'b0;
            end
        end else if (cfg_we) begin
            case (cfg_addr[5:4])
                2'b00: w_reg[cfg_addr[3:0]] <= cfg_wdata;
                2'b01: t_reg[cfg_addr[3:0]] <= cfg_wdata[6:0];
                default: ;
            endcase
        end
    end

    tile_tlg_ld_neuron u_n00 (.x(x_reg), .w(w_reg[0]), .threshold(t_reg[0]), .y(y_comb[0]));
    tile_tlg_ld_neuron u_n01 (.x(x_reg), .w(w_reg[1]), .threshold(t_reg[1]), .y(y_comb[1]));
    tile_tlg_ld_neuron u_n02 (.x(x_reg), .w(w_reg[2]), .threshold(t_reg[2]), .y(y_comb[2]));
    tile_tlg_ld_neuron u_n03 (.x(x_reg), .w(w_reg[3]), .threshold(t_reg[3]), .y(y_comb[3]));
    tile_tlg_ld_neuron u_n04 (.x(x_reg), .w(w_reg[4]), .threshold(t_reg[4]), .y(y_comb[4]));
    tile_tlg_ld_neuron u_n05 (.x(x_reg), .w(w_reg[5]), .threshold(t_reg[5]), .y(y_comb[5]));
    tile_tlg_ld_neuron u_n06 (.x(x_reg), .w(w_reg[6]), .threshold(t_reg[6]), .y(y_comb[6]));
    tile_tlg_ld_neuron u_n07 (.x(x_reg), .w(w_reg[7]), .threshold(t_reg[7]), .y(y_comb[7]));
    tile_tlg_ld_neuron u_n08 (.x(x_reg), .w(w_reg[8]), .threshold(t_reg[8]), .y(y_comb[8]));
    tile_tlg_ld_neuron u_n09 (.x(x_reg), .w(w_reg[9]), .threshold(t_reg[9]), .y(y_comb[9]));
    tile_tlg_ld_neuron u_n10 (.x(x_reg), .w(w_reg[10]), .threshold(t_reg[10]), .y(y_comb[10]));
    tile_tlg_ld_neuron u_n11 (.x(x_reg), .w(w_reg[11]), .threshold(t_reg[11]), .y(y_comb[11]));
    tile_tlg_ld_neuron u_n12 (.x(x_reg), .w(w_reg[12]), .threshold(t_reg[12]), .y(y_comb[12]));
    tile_tlg_ld_neuron u_n13 (.x(x_reg), .w(w_reg[13]), .threshold(t_reg[13]), .y(y_comb[13]));
    tile_tlg_ld_neuron u_n14 (.x(x_reg), .w(w_reg[14]), .threshold(t_reg[14]), .y(y_comb[14]));
    tile_tlg_ld_neuron u_n15 (.x(x_reg), .w(w_reg[15]), .threshold(t_reg[15]), .y(y_comb[15]));
endmodule
`default_nettype wire
